# Generated by Django 5.0.1 on 2024-03-08 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sotuv',
            name='qarz',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
