# Generated by Django 5.0.1 on 2024-03-05 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('brend', models.CharField(blank=True, max_length=258, null=True)),
                ('narx1', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('narx2', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('miqdor', models.PositiveIntegerField(default=1)),
                ('olchov', models.CharField(max_length=50)),
                ('sana', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('dokon', models.CharField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(max_length=14)),
                ('manzil', models.TextField()),
            ],
        ),
    ]
