# Generated by Django 5.0.1 on 2024-03-08 05:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mijoz',
            name='qarz',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
